title: Robotic Systems Labs
description: A location to provide access to all the EGR 455 and 456 labs along with supporting materials. Hope this help.
remote_theme: just-the-docs/just-the-docs@v0.8.1

# url: https://just-the-docs.github.io
url: " "

hide_icon: true # set to true to hide the external link icon - defaults to false

opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
aux_links:
  ASU Canvas Link: https://canvas.asu.edu

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Kevin Nichols. This site is powered by Netlify.</a>"


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

